apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-loader
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      containers:
      - name: data-loader
        image: idanshan/data-loader-fastapi
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
---
apiVersion: v1
kind: Service
metadata:
  name: data-loader
spec:
  ports:
  - port: 8000
  selector:
    app: data-loader